---
- name: Install EPEL
  ansible.builtin.package:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- name: Install base packages
  retries: 10
  delay: 5
  ansible.builtin.package:
    name:
      - python-pip
    state: present

- name: ADD THE EXTRAS REPO
  ansible.builtin.shell: yum-config-manager --enable rhui-REGION-rhel-server-extras

- name: ENSURE THAT DOCKER IS INSTALLED
  ansible.builtin.package:
    name: docker
    state: present

- name: ENSURE THAT DOCKER DAEMON IS STARTED
  ansible.builtin.service:
    name: docker
    state: started
